import Head from "next/head";
import Layout from "@/components/Layout";
import Hero from "@/components/Hero";
import Movies from "@/components/Movies";
import Shows from "@/components/Shows";
import { getSession, useSession } from "next-auth/react";
import { GetServerSideProps } from "next";
import Trending from "@/components/Trending";
import Discover from "@/components/Discover";
import BannerHome from "@/components/BannerHome";

type Props = any;

export default function Home({
  popularMovies,
  popularShows,
  top_ratedMovies,
  top_ratedShows,
  trending,
  discover,
}: Props) {
  const { data: session, status } = useSession();

  console.log(status);
  return (
    <Layout>
      <Head>
        <title>Next Disney+</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/disney-logo.svg" />
      </Head>

      {!session ? (
        <Hero />
      ) : (
        <main className="container mx-auto px-5 md:px-0">
          <BannerHome />
          <Trending data={trending} />
          <Movies data={popularMovies} title="Popular Movies" />
          <Movies data={top_ratedMovies} title="Top Rated Movies" />
          <Shows data={popularShows} title="Popular Shows" />
          <Shows data={top_ratedShows} title="Top Rated Shows" />
          <Discover data={discover} title="Horror Movies" />
        </main>
      )}
    </Layout>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);

  const [
    popularMoviesRes,
    popularShowRes,
    top_ratedMoviesRes,
    top_ratedShowRes,
    trendingRes,
    discoverRes,
    mcuRes,
  ] = await Promise.all([
    fetch(
      `https://api.themoviedb.org/3/movie/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/tv/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/tv/top_rated?api_key=${process.env.API_KEY}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/trending/all/day?api_key=${process.env.API_KEY}`
    ),
    fetch(
      `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.API_KEY}&language=en-US&with_genres=27&sort_by=revenue.desc`
    ),
    fetch(
      `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.API_KEY}&language=en-US&production_companies=420&sort_by=popularity.desc`
    ),
  ]);

  const [
    popularMovies,
    popularShows,
    top_ratedMovies,
    top_ratedShows,
    trending,
    discover,
    mcu,
  ] = await Promise.all([
    popularMoviesRes.json(),
    popularShowRes.json(),
    top_ratedMoviesRes.json(),
    top_ratedShowRes.json(),
    trendingRes.json(),
    discoverRes.json(),
    mcuRes.json(),
  ]);
  return {
    props: {
      session,
      popularMovies: popularMovies?.results || null,
      popularShows: popularShows?.results || null,
      top_ratedMovies: top_ratedMovies?.results || null,
      top_ratedShows: top_ratedShows?.results || null,
      trending: trending.results,
      discover: discover.results,
      mcu,
    },
  };
};
